[package]
name = "utils"
edition = "2024"

[dependencies]
itertools.workspace = true
num-traits.workspace = true
serde.workspace = true
anyhow.workspace = true
ron.workspace = true
bevy.workspace = true