[package]
name = "player"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_panorbit_camera.workspace = true
debug_resource.workspace = true
physics.workspace = true
world_generation.workspace = true
bevy_egui.workspace = true