[package]
name = "player"
edition = "2024"

[dependencies]
bevy.workspace = true
debug_resource.workspace = true
physics.workspace = true
world_generation.workspace = true
bevy_egui.workspace = true
serde.workspace = true
bevy_hookup_core.workspace = true
utils.workspace = true